
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vcasotti
 */
public class CADAStro_FUNCIONARIOS extends javax.swing.JFrame {
 public class DatabaseConnection {
    private final String URL = "jdbc:mysql://localhost:/sistema";
        private final String USER = "root";
        private final String PASSWORD = "";
        
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }
  
    // Outros métodos e lógica aqui

    /**
     * Creates new form CADAStro_FUNCIONARIOS
     */
    public CADAStro_FUNCIONARIOS() {
        initComponents();
 VOLTA_INICIO.setBackground (new java.awt.Color(0,0,0,0)); 
 try {
            // Máscara para CPF
            MaskFormatter maskCPF = new MaskFormatter("###.###.###-##");
            maskCPF.setPlaceholderCharacter('_');
            maskCPF.install((JFormattedTextField) txt_cpf);

            // Máscara para data de nascimento
            MaskFormatter maskDataNascimento = new MaskFormatter("##/##/####");
            maskDataNascimento.setPlaceholderCharacter('_');
            maskDataNascimento.install((JFormattedTextField) dt_nascimento);

        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_MN_cadastro_F = new javax.swing.JButton();
        cb_estoque = new javax.swing.JComboBox<>();
        cb_relatorios = new javax.swing.JComboBox<>();
        VOLTA_INICIO = new javax.swing.JButton();
        listas = new javax.swing.JComboBox<>();
        nome = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        carteira_trabalho = new javax.swing.JTextField();
        sexo = new javax.swing.JTextField();
        estado_civil = new javax.swing.JTextField();
        escolaridade = new javax.swing.JTextField();
        cargo = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        btn_mostra_lista = new javax.swing.JButton();
        BTN_SALVAR = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        dt_nascimento = new javax.swing.JFormattedTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        BTN_MOTRA_LISTA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_MN_cadastro_F.setText("jButton2");
        btn_MN_cadastro_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MN_cadastro_FActionPerformed(evt);
            }
        });
        jPanel1.add(btn_MN_cadastro_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 50));

        cb_estoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visão Geral", "Entrada de epis", "Epi para funcionarios", " " }));
        cb_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(cb_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 60));

        cb_relatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relatorio do Estoque", "Relatorio de  Entrega" }));
        cb_relatorios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_relatoriosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cb_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_relatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(cb_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, 70));

        VOLTA_INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTA_INICIOActionPerformed(evt);
            }
        });
        jPanel1.add(VOLTA_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        listas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EPI em Estoque", "Funcionarios  Cadastrados", "EPI Entregue", " " }));
        listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasActionPerformed(evt);
            }
        });
        jPanel1.add(listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 70));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 440, -1));

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        jPanel1.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 440, -1));

        carteira_trabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carteira_trabalhoActionPerformed(evt);
            }
        });
        jPanel1.add(carteira_trabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 180, -1));

        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 180, -1));

        estado_civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_civilActionPerformed(evt);
            }
        });
        jPanel1.add(estado_civil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 170, 30));
        jPanel1.add(escolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 120, 30));

        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });
        jPanel1.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 120, 20));

        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setActionCommand(null);
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 120, 20));

        btn_mostra_lista.setText("jButton1");
        btn_mostra_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostra_listaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mostra_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 170, 30));

        BTN_SALVAR.setText("jButton2");
        BTN_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALVARActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_SALVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 150, 30));

        btn_cancelar.setText("jButton2");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 140, 30));

        dt_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_nascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(dt_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 450, -1));
        jPanel1.add(txt_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 120, -1));

        BTN_MOTRA_LISTA.setIcon(new javax.swing.ImageIcon("C:\\Users\\vitor\\Desktop\\EPI_gestor\\EPI_Gestor\\EPI_Gestor\\src\\main\\java\\com\\telas\\epi_gestor\\telas\\CADASTRO DE FUNCIONARIOS.png")); // NOI18N
        BTN_MOTRA_LISTA.setText("jLabel1");
        jPanel1.add(BTN_MOTRA_LISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 804, 528));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MN_cadastro_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MN_cadastro_FActionPerformed
        
    }//GEN-LAST:event_btn_MN_cadastro_FActionPerformed

    private void cb_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estoqueActionPerformed
        String selectedOption = (String) cb_estoque.getSelectedItem();

        if ("Visão Geral".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            VISAO_GERAL_ESTOQUE VisaoGeralEstoque = new VISAO_GERAL_ESTOQUE();
            VisaoGeralEstoque.setVisible(true);
        } else if ("Entrada de epis".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            ENTRADA_pei_estoque EntradaEpiEstoque = new ENTRADA_pei_estoque();
            EntradaEpiEstoque.setVisible(true);
        } else if ("Epi para funcionarios".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            ENTRADA_epi_funcionarios SaidaParaFuncionarios = new ENTRADA_epi_funcionarios();
            SaidaParaFuncionarios.setVisible(true);
        }
    }//GEN-LAST:event_cb_estoqueActionPerformed

    private void cb_relatoriosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_relatoriosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_relatoriosAncestorAdded

    private void cb_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_relatoriosActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)  cb_relatorios.getSelectedItem();

        if ("Relatorio do Estoque".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            RELATORIO_ESTOQUE relatorioEstoque = new RELATORIO_ESTOQUE();
            relatorioEstoque.setVisible(true);
        } else if ("Relatorio de  Entrega".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            RELATORIO_ENTREGA_FUNCIONARIO EntregaEpiEstoque = new RELATORIO_ENTREGA_FUNCIONARIO();
            EntregaEpiEstoque.setVisible(true);
        }
    }//GEN-LAST:event_cb_relatoriosActionPerformed

    private void VOLTA_INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTA_INICIOActionPerformed

        CADAStro_FUNCIONARIOS.this.dispose();
        MENU  VOLTA_INICIO = new MENU();
         VOLTA_INICIO.setVisible(true);
         
    }//GEN-LAST:event_VOLTA_INICIOActionPerformed

    private void listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)listas.getSelectedItem();

        if ("EPI em Estoque".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            LISTA_EPI_EMESTOQUE listaEstoque = new LISTA_EPI_EMESTOQUE();
            listaEstoque.setVisible(true);
        } else if ("Funcionarios  Cadastrados".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            LISTA_FUNCIONARIOS lisEpiEntrgue = new LISTA_FUNCIONARIOS();
            lisEpiEntrgue.setVisible(true);
        } else if ("EPI Entregue".equals(selectedOption)) {
            CADAStro_FUNCIONARIOS.this.dispose();
            EPI_ENTREGUE lisEpiEntrgue = new EPI_ENTREGUE();
            lisEpiEntrgue.setVisible(true);
        }
    }//GEN-LAST:event_listasActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
 CADAStro_FUNCIONARIOS.this.dispose();
        MENU  btn_cancelar = new MENU();
         btn_cancelar.setVisible(true);        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void BTN_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALVARActionPerformed
           String nomeFuncionario = nome.getText();
        String dataNascimento = dt_nascimento.getText();
        String enderecoFuncionario = endereco.getText();
        String cargoFuncionario = cargo.getText();
        String cpfFuncionario = txt_cpf.getText();
        String sexoFuncionario = sexo.getText();
        String estadoCivilFuncionario = estado_civil.getText();
        String carteiraTrabalhoFuncionario = carteira_trabalho.getText();

        // Validação: Verificar se algum campo está vazio
        if (nomeFuncionario.isEmpty() || dataNascimento.isEmpty() || enderecoFuncionario.isEmpty() ||
                cargoFuncionario.isEmpty() || cpfFuncionario.isEmpty() || sexoFuncionario.isEmpty() ||
                estadoCivilFuncionario.isEmpty() || carteiraTrabalhoFuncionario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!");
        } else if (!cpfFuncionario.matches("\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}")) { // Verifica se o CPF está no formato correto
            JOptionPane.showMessageDialog(this, "O CPF deve estar no formato correto: ###.###.###-##");
        } else {
            try {
                // Conectar ao banco de dados
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:/sistema", "root", "");

                // Formatador para a data de nascimento
                SimpleDateFormat formatadorData = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date data = formatadorData.parse(dataNascimento);
                java.sql.Date dataSql = new java.sql.Date(data.getTime());

                // Preparar a inserção dos dados na tabela Funcionarios
                String sql = "INSERT INTO Funcionarios (nome, data_nascimento, endereco, cargo, cpf, sexo, estado_civil, carteira_trabalho) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, nomeFuncionario);
                stmt.setDate(2, dataSql); // data_nascimento
                stmt.setString(3, enderecoFuncionario);
                stmt.setString(4, cargoFuncionario);
                stmt.setString(5, cpfFuncionario);
                stmt.setString(6, sexoFuncionario);
                stmt.setString(7, estadoCivilFuncionario);
                stmt.setString(8, carteiraTrabalhoFuncionario);

                // Executar a inserção dos dados
                int rowsAffected = stmt.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
                    limparCampos(); // Limpar os campos após o cadastro ser bem-sucedido
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar funcionário!");
                }
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + ex.getMessage());
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data de nascimento inválida. Informe no formato dd/MM/yyyy.");
            }
        }
    }

    // Método para limpar os campos
    private void limparCampos() {
        nome.setText("");
        dt_nascimento.setText("");
        endereco.setText("");
        cargo.setText("");
        txt_cpf.setText("");
        sexo.setText("");
        estado_civil.setText("");
        carteira_trabalho.setText("");
    
    }//GEN-LAST:event_BTN_SALVARActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void carteira_trabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carteira_trabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carteira_trabalhoActionPerformed

    private void estado_civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_civilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_civilActionPerformed

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    private void btn_mostra_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostra_listaActionPerformed
        // TODO add your handling code here:
         LISTA_FUNCIONARIOS listaFuncionarios = new LISTA_FUNCIONARIOS();
        listaFuncionarios.setVisible(true);
        listaFuncionarios.preencherTabela();
    }//GEN-LAST:event_btn_mostra_listaActionPerformed

    private void dt_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_nascimentoActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CADAStro_FUNCIONARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CADAStro_FUNCIONARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CADAStro_FUNCIONARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADAStro_FUNCIONARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CADAStro_FUNCIONARIOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BTN_MOTRA_LISTA;
    private javax.swing.JButton BTN_SALVAR;
    private javax.swing.JButton VOLTA_INICIO;
    private javax.swing.JButton btn_MN_cadastro_F;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_mostra_lista;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField carteira_trabalho;
    private javax.swing.JComboBox<String> cb_estoque;
    private javax.swing.JComboBox<String> cb_relatorios;
    private javax.swing.JFormattedTextField dt_nascimento;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField escolaridade;
    private javax.swing.JTextField estado_civil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JComboBox<String> listas;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField sexo;
    private javax.swing.JFormattedTextField txt_cpf;
    // End of variables declaration//GEN-END:variables
}
