
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vitor
 */
public class ENTRADA_pei_estoque extends javax.swing.JFrame {

    /**
     * Creates new form ENTRADA_pei_estoque
     */
    public ENTRADA_pei_estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_proximo = new javax.swing.JButton();
        VOLTA_INICIO = new javax.swing.JButton();
        btn_MN_cadastro_F = new javax.swing.JButton();
        cb_estoque = new javax.swing.JComboBox<>();
        cb_relatorios = new javax.swing.JComboBox<>();
        listas = new javax.swing.JComboBox<>();
        TXT_tipoEPI = new javax.swing.JTextField();
        txt_quantidade = new javax.swing.JTextField();
        txt_IDpedido = new javax.swing.JTextField();
        txt_validade = new javax.swing.JTextField();
        txt_Fonercedor = new javax.swing.JTextField();
        txt_DT_entrada = new javax.swing.JTextField();
        BTN_SALVAR = new javax.swing.JButton();
        salvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_proximo.setText("jButton1");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 190, 30));

        VOLTA_INICIO.setText("jButton1");
        VOLTA_INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTA_INICIOActionPerformed(evt);
            }
        });
        jPanel1.add(VOLTA_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 40));

        btn_MN_cadastro_F.setText("jButton2");
        btn_MN_cadastro_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MN_cadastro_FActionPerformed(evt);
            }
        });
        jPanel1.add(btn_MN_cadastro_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 50));

        cb_estoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visão Geral", "Entrada de epis", "Epi para funcionarios", " " }));
        cb_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(cb_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 180, 170, 60));

        cb_relatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relatorio do Estoque", "Relatorio de  Entrega" }));
        cb_relatorios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_relatoriosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cb_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_relatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(cb_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 290, -1, 70));

        listas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EPI em Estoque", "Funcionarios  Cadastrados", "EPI Entregue", " " }));
        listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasActionPerformed(evt);
            }
        });
        jPanel1.add(listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 390, -1, 70));

        TXT_tipoEPI.setText("jTextField1");
        TXT_tipoEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_tipoEPIActionPerformed(evt);
            }
        });
        jPanel1.add(TXT_tipoEPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 162, 220, 30));

        txt_quantidade.setText("jTextField2");
        txt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 160, 250, -1));

        txt_IDpedido.setText("jTextField3");
        txt_IDpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDpedidoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_IDpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 230, -1));

        txt_validade.setText("jTextField4");
        txt_validade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_validadeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_validade, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 240, -1));

        txt_Fonercedor.setText("jTextField5");
        txt_Fonercedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FonercedorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Fonercedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 230, -1));

        txt_DT_entrada.setText("jTextField6");
        txt_DT_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DT_entradaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_DT_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 240, -1));

        BTN_SALVAR.setText("SALVAR");
        BTN_SALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALVARActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_SALVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/telas/epi_gestor/telas/ENTRADA_FUNCIONARIO.png"))); // NOI18N
        salvar.setText("jLabel1");
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 790, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
                                                
    // Implemente o código para passar para a próxima tela apenas se os dados estiverem salvos
    // Você pode adicionar uma verificação aqui, por exemplo:
    
    // Verificar se os dados foram salvos com sucesso
    boolean dadosSalvos = dadosForamSalvos();
    
    // Se os dados foram salvos com sucesso, passar para a próxima tela
    if (dadosSalvos) {
        passarParaProximaTela();
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, salve os dados antes de prosseguir.");
    }
}

private boolean dadosForamSalvos() {
    // Implemente a lógica para verificar se os dados foram salvos com sucesso
    // Por exemplo, você pode verificar se os campos obrigatórios foram preenchidos corretamente
    // e se a inserção no banco de dados foi bem-sucedida.
    // Por enquanto, retornaremos true apenas para fins de exemplo.
    return true;      
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void VOLTA_INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTA_INICIOActionPerformed
        ENTRADA_pei_estoque.this.dispose();
        MENU  VOLTA_INICIO = new MENU();
        VOLTA_INICIO.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_VOLTA_INICIOActionPerformed

    private void btn_MN_cadastro_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MN_cadastro_FActionPerformed
        // TODO add your handling code here:
        ENTRADA_pei_estoque.this.dispose();
        CADAStro_FUNCIONARIOS btn_MN_cadastro_F = new CADAStro_FUNCIONARIOS();
        btn_MN_cadastro_F.setVisible(true);
    }//GEN-LAST:event_btn_MN_cadastro_FActionPerformed

    private void cb_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estoqueActionPerformed
        String selectedOption = (String) cb_estoque.getSelectedItem();

        if ("Visão Geral".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            VISAO_GERAL_ESTOQUE VisaoGeralEstoque = new VISAO_GERAL_ESTOQUE();
            VisaoGeralEstoque.setVisible(true);
        
        }
    }//GEN-LAST:event_cb_estoqueActionPerformed

    private void cb_relatoriosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_relatoriosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_relatoriosAncestorAdded

    private void cb_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_relatoriosActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)  cb_relatorios.getSelectedItem();

        if ("Relatorio do Estoque".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            RELATORIO_ESTOQUE relatorioEstoque = new RELATORIO_ESTOQUE();
            relatorioEstoque.setVisible(true);
        } else if ("Relatorio de  Entrega".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            RELATORIO_ENTREGA_FUNCIONARIO EntregaEpiEstoque = new RELATORIO_ENTREGA_FUNCIONARIO();
            EntregaEpiEstoque.setVisible(true);
        }
    }//GEN-LAST:event_cb_relatoriosActionPerformed

    private void listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)listas.getSelectedItem();

        if ("EPI em Estoque".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            LISTA_EPI_EMESTOQUE listaEstoque = new LISTA_EPI_EMESTOQUE();
            listaEstoque.setVisible(true);
        } else if ("Funcionarios  Cadastrados".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            LISTA_FUNCIONARIOS lisEpiEntrgue = new LISTA_FUNCIONARIOS();
            lisEpiEntrgue.setVisible(true);
        } else if ("EPI Entregue".equals(selectedOption)) {
            ENTRADA_pei_estoque.this.dispose();
            EPI_ENTREGUE lisEpiEntrgue = new EPI_ENTREGUE();
            lisEpiEntrgue.setVisible(true);
        }
    }//GEN-LAST:event_listasActionPerformed

    private void txt_validadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_validadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_validadeActionPerformed

    private void TXT_tipoEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_tipoEPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_tipoEPIActionPerformed

    private void txt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeActionPerformed

    private void txt_IDpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDpedidoActionPerformed

    private void txt_FonercedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FonercedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FonercedorActionPerformed

    private void txt_DT_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DT_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DT_entradaActionPerformed

    private void BTN_SALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALVARActionPerformed
        // TODO add your handling code here:
         String validade = txt_validade.getText();
    String tipoEPI = TXT_tipoEPI.getText();
    String quantidade = txt_quantidade.getText();
    String IDpedido = txt_IDpedido.getText();
    String fornecedor = txt_Fonercedor.getText();
    String dataEntrada = txt_DT_entrada.getText();

    // Conectar ao banco de dados e inserir os valores
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/seu_banco_de_dados", "seu_usuario", "sua_senha");
        String sql = "INSERT INTO SuaTabela (validade, tipoEPI, quantidade, IDpedido, fornecedor, dataEntrada) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, validade);
        stmt.setString(2, tipoEPI);
        stmt.setString(3, quantidade);
        stmt.setString(4, IDpedido);
        stmt.setString(5, fornecedor);
        stmt.setString(6, dataEntrada);
        
        int rowsAffected = stmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar os dados!");
        }
        
        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + ex.getMessage());
    }
    }//GEN-LAST:event_BTN_SALVARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_pei_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_pei_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_pei_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_pei_estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ENTRADA_pei_estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_SALVAR;
    private javax.swing.JTextField TXT_tipoEPI;
    private javax.swing.JButton VOLTA_INICIO;
    private javax.swing.JButton btn_MN_cadastro_F;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JComboBox<String> cb_estoque;
    private javax.swing.JComboBox<String> cb_relatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listas;
    private javax.swing.JLabel salvar;
    private javax.swing.JTextField txt_DT_entrada;
    private javax.swing.JTextField txt_Fonercedor;
    private javax.swing.JTextField txt_IDpedido;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_validade;
    // End of variables declaration//GEN-END:variables

    private void passarParaProximaTela() {
        // Criar e exibir a próxima tela
    PASSO_2_ENTRADA_EPI telaPasso2 = new PASSO_2_ENTRADA_EPI();
    telaPasso2.setVisible(true);
    
    // Fechar a tela atual
    this.dispose();
}
}
