

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vcasotti
 */
public class ENTRADA_epi_funcionarios extends javax.swing.JFrame {
   
   
  private final String URL = "jdbc:mysql://localhost:/sistema";
        private final String USER = "root";
        private final String PASSWORD = "";
        
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    /**
     * Creates new form ENTREGA_DE_EPI
     */
    public ENTRADA_epi_funcionarios() {
        initComponents();
         addDocumentListenerToNomeEpi();
         // Inicialmente, todos os botões e campos de texto são tornados invisíveis
txt_nome_funcionario.setBackground (new java.awt.Color(0,0,0,1));
id_doEPI.setBackground (new java.awt.Color(0,0,0,1));
nome_doEPI .setBackground (new java.awt.Color(0,0,0,1));
TXT_tipo_epi .setBackground (new java.awt.Color(0,0,0,1));
txt_quantidade .setBackground (new java.awt.Color(0,0,0,1));
txt_proteçao .setBackground (new java.awt.Color(0,0,0,1));
        VOLTA_INICIO .setBackground (new java.awt.Color(0,0,0,0)); 
btn_MN_cadastro_F.setBackground (new java.awt.Color(0,0,0,0)); 
BTN_SALVA1 .setBackground (new java.awt.Color(0,0,0,0)); 
jButton2 .setBackground (new java.awt.Color(0,0,0,0)); 
MOSTRA_LISTA1 .setBackground (new java.awt.Color(0,0,0,0));    
cb_estoque .setBackground (new java.awt.Color(0,0,0,0)); 
cb_relatorios.setBackground (new java.awt.Color(0,0,0,0));  
listas.setBackground (new java.awt.Color(0,0,0,0)); 
        
        
    }

     
    
    private void addDocumentListenerToNomeEpi() {
          
        nome_doEPI.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                buscarIdEpi(nome_doEPI.getText().trim());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                buscarIdEpi(nome_doEPI.getText().trim());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Não utilizado para campos de texto simples
            }
        });
    }

    private void buscarIdEpi(String nomeEpi) {
        String sql = "SELECT id_epi FROM EntradaEPI WHERE nome_epi = ?";
        int idEpi = -1;

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, nomeEpi);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    idEpi = rs.getInt("id_epi");
                    id_doEPI.setText(String.valueOf(idEpi));
                } else {
                    id_doEPI.setText("");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar ID do EPI: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            id_doEPI.setText("");
        }
    }
          
    public class DatabaseConnection {
    private final String URL = "jdbc:mysql://localhost:/sistema";
        private final String USER = "root";
        private final String PASSWORD = "";
        
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(URL, USER, PASSWORD); }

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VOLTA_INICIO = new javax.swing.JButton();
        btn_MN_cadastro_F = new javax.swing.JButton();
        cb_estoque = new javax.swing.JComboBox<>();
        cb_relatorios = new javax.swing.JComboBox<>();
        listas = new javax.swing.JComboBox<>();
        BTN_SALVA1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MOSTRA_LISTA1 = new javax.swing.JButton();
        txt_nome_funcionario = new javax.swing.JTextField();
        id_doEPI = new javax.swing.JTextField();
        nome_doEPI = new javax.swing.JTextField();
        TXT_tipo_epi = new javax.swing.JTextField();
        txt_quantidade = new javax.swing.JTextField();
        txt_proteçao = new javax.swing.JTextField();
        BTN_VOLTA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VOLTA_INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTA_INICIOActionPerformed(evt);
            }
        });
        jPanel1.add(VOLTA_INICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        btn_MN_cadastro_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MN_cadastro_FActionPerformed(evt);
            }
        });
        jPanel1.add(btn_MN_cadastro_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 90, 150, 80));

        cb_estoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Visão Geral", "Entrada de epis", "Epi para funcionarios", " " }));
        cb_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estoqueActionPerformed(evt);
            }
        });
        jPanel1.add(cb_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 180, -1, 90));

        cb_relatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Relatorio do Estoque", "Relatorio de  Entrega" }));
        cb_relatorios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cb_relatoriosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cb_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_relatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(cb_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 290, 120, 90));

        listas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "EPI em Estoque", "Funcionarios  Cadastrados", "EPI Entregue", " " }));
        listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasActionPerformed(evt);
            }
        });
        jPanel1.add(listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 400, 140, 90));

        BTN_SALVA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALVA1ActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_SALVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 150, 40));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 150, 40));

        MOSTRA_LISTA1.setBorder(null);
        MOSTRA_LISTA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRA_LISTA1ActionPerformed(evt);
            }
        });
        jPanel1.add(MOSTRA_LISTA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 150, 40));

        txt_nome_funcionario.setBorder(null);
        txt_nome_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_funcionarioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nome_funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 20));

        id_doEPI.setBorder(null);
        id_doEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_doEPIActionPerformed(evt);
            }
        });
        jPanel1.add(id_doEPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 240, 30));

        nome_doEPI.setBorder(null);
        nome_doEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_doEPIActionPerformed(evt);
            }
        });
        jPanel1.add(nome_doEPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 268, 240, 20));

        TXT_tipo_epi.setBorder(null);
        TXT_tipo_epi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_tipo_epiActionPerformed(evt);
            }
        });
        jPanel1.add(TXT_tipo_epi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 240, 20));

        txt_quantidade.setBorder(null);
        txt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 230, 20));

        txt_proteçao.setBorder(null);
        txt_proteçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proteçaoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_proteçao, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 250, 30));

        BTN_VOLTA.setIcon(new javax.swing.ImageIcon("C:\\Users\\vitor\\Desktop\\EPI_gestor\\EPI_Gestor\\EPI_Gestor\\src\\main\\java\\com\\telas\\epi_gestor\\telas\\TELA_EPIS para os funcionarios.png")); // NOI18N
        BTN_VOLTA.setText("jLabel2");
        jPanel1.add(BTN_VOLTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 790, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTA_INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTA_INICIOActionPerformed
ENTRADA_epi_funcionarios.this.dispose();
        MENU  VOLTA_INICIO = new MENU();
         VOLTA_INICIO.setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_VOLTA_INICIOActionPerformed

    private void btn_MN_cadastro_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MN_cadastro_FActionPerformed
        // TODO add your handling code here:
        ENTRADA_epi_funcionarios.this.dispose();
        CADAStro_FUNCIONARIOS btn_MN_cadastro_F = new CADAStro_FUNCIONARIOS();
        btn_MN_cadastro_F.setVisible(true);
    }//GEN-LAST:event_btn_MN_cadastro_FActionPerformed

    private void cb_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estoqueActionPerformed
        String selectedOption = (String) cb_estoque.getSelectedItem();

        if ("Visão Geral".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            VISAO_GERAL_ESTOQUE VisaoGeralEstoque = new VISAO_GERAL_ESTOQUE();
            VisaoGeralEstoque.setVisible(true);
        } else if ("Entrada de epis".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            ENTRADA_pei_estoque EntradaEpiEstoque = new ENTRADA_pei_estoque();
            EntradaEpiEstoque.setVisible(true);
        
        }
    }//GEN-LAST:event_cb_estoqueActionPerformed

    private void cb_relatoriosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cb_relatoriosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_relatoriosAncestorAdded

    private void cb_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_relatoriosActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)  cb_relatorios.getSelectedItem();

        if ("Relatorio do Estoque".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            RELATORIO_ESTOQUE relatorioEstoque = new RELATORIO_ESTOQUE();
            relatorioEstoque.setVisible(true);
        } else if ("Relatorio de  Entrega".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            RELATORIO_ENTREGA_FUNCIONARIO EntregaEpiEstoque = new RELATORIO_ENTREGA_FUNCIONARIO();
            EntregaEpiEstoque.setVisible(true);
        }
    }//GEN-LAST:event_cb_relatoriosActionPerformed

    private void listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String)listas.getSelectedItem();

        if ("EPI em Estoque".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            LISTA_EPI_EMESTOQUE listaEstoque = new LISTA_EPI_EMESTOQUE();
            listaEstoque.setVisible(true);
        } else if ("Funcionarios  Cadastrados".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            LISTA_FUNCIONARIOS lisEpiEntrgue = new LISTA_FUNCIONARIOS();
            lisEpiEntrgue.setVisible(true);
        } else if ("EPI Entregue".equals(selectedOption)) {
            ENTRADA_epi_funcionarios.this.dispose();
            EPI_ENTREGUE lisEpiEntrgue = new EPI_ENTREGUE();
            lisEpiEntrgue.setVisible(true);
        }
    }//GEN-LAST:event_listasActionPerformed

    private void BTN_SALVA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALVA1ActionPerformed
        if (txt_nome_funcionario.getText().trim().isEmpty() ||
            id_doEPI.getText().trim().isEmpty() ||
            nome_doEPI.getText().trim().isEmpty() ||
            TXT_tipo_epi.getText().trim().isEmpty() ||
            txt_quantidade.getText().trim().isEmpty() ||
            txt_proteçao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String url = "jdbc:mysql://localhost:/sistema";
        String user = "root";
        String password = "";

        String sql = "INSERT INTO epi_para_funcionarios(nome_funcionario, id_epi, nome_epi, tipo_epi, quantidade, protecao) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, password);
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, txt_nome_funcionario.getText());
            pstmt.setInt(2, Integer.parseInt(id_doEPI.getText()));
            pstmt.setString(3, nome_doEPI.getText());
            pstmt.setString(4, TXT_tipo_epi.getText());
            pstmt.setInt(5, Integer.parseInt(txt_quantidade.getText()));
            pstmt.setString(6, txt_proteçao.getText());

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar dados: " + e.getMessage());
        }
    
    }//GEN-LAST:event_BTN_SALVA1ActionPerformed

    private void MOSTRA_LISTA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRA_LISTA1ActionPerformed
     EPI_ENTREGUE ENTREGUE = new EPI_ENTREGUE();
        ENTREGUE.setVisible(true);
        ENTREGUE. preencherTabela3();
    
    }//GEN-LAST:event_MOSTRA_LISTA1ActionPerformed

    private void nome_doEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_doEPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_doEPIActionPerformed

    private void txt_nome_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_funcionarioActionPerformed

    private void id_doEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_doEPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_doEPIActionPerformed

    private void TXT_tipo_epiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_tipo_epiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_tipo_epiActionPerformed

    private void txt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeActionPerformed

    private void txt_proteçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proteçaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proteçaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_epi_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_epi_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_epi_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ENTRADA_epi_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ENTRADA_epi_funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_SALVA1;
    private javax.swing.JLabel BTN_VOLTA;
    private javax.swing.JButton MOSTRA_LISTA1;
    private javax.swing.JTextField TXT_tipo_epi;
    private javax.swing.JButton VOLTA_INICIO;
    private javax.swing.JButton btn_MN_cadastro_F;
    private javax.swing.JComboBox<String> cb_estoque;
    private javax.swing.JComboBox<String> cb_relatorios;
    private javax.swing.JTextField id_doEPI;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> listas;
    private javax.swing.JTextField nome_doEPI;
    private javax.swing.JTextField txt_nome_funcionario;
    private javax.swing.JTextField txt_proteçao;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
