/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.epi_gestor.sistema;

import javax.swing.JComboBox;

/**
 *
 * @author vitor
 */
public class TELA_menu extends javax.swing.JFrame {

    /**
     * Creates new form TELA_menu
     */
    public TELA_menu() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_MN_cadastro_F = new javax.swing.JButton();
        btn_MN_epi_entregue = new javax.swing.JButton();
        CB_listas = new javax.swing.JComboBox<>();
        CB_estoque = new javax.swing.JComboBox<>();
        cb_relatorios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_MN_cadastro_F.setText("jButton1");
        btn_MN_cadastro_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MN_cadastro_FActionPerformed(evt);
            }
        });
        jPanel2.add(btn_MN_cadastro_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        btn_MN_epi_entregue.setText("jButton1");
        btn_MN_epi_entregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MN_epi_entregueActionPerformed(evt);
            }
        });
        jPanel2.add(btn_MN_epi_entregue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 60));

        CB_listas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_listasActionPerformed(evt);
            }
        });
        jPanel2.add(CB_listas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 422, -1, 50));

        CB_estoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visao Geral do Estoque", "Entrada EPI Estoque", "Saida para funcionarios" }));
        CB_estoque.setToolTipText("");
        CB_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_estoqueActionPerformed(evt);
            }
        });
        jPanel2.add(CB_estoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 60));

        cb_relatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relatorio Entrega Funcionarios", "Relatorio De Estoque" }));
        cb_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_relatoriosActionPerformed(evt);
            }
        });
        jPanel2.add(cb_relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\vitor\\Desktop\\EPI_gestor\\EPI_Gestor\\EPI_Gestor\\src\\main\\java\\com\\telas\\epi_gestor\\telas\\TL_menu.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 800, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MN_epi_entregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MN_epi_entregueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MN_epi_entregueActionPerformed

    private void btn_MN_cadastro_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MN_cadastro_FActionPerformed
        TELA_menu.this.dispose();
        TELA_cadastro_funcionarios btn_MN_cadastro_F = new TELA_cadastro_funcionarios();
        btn_MN_cadastro_F.setVisible(true);
    
   
    }//GEN-LAST:event_btn_MN_cadastro_FActionPerformed

    private void CB_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_estoqueActionPerformed
         String selectedOption = (String) CB_estoque.getSelectedItem();

        if ("Visao Geral do Estoque".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_visao_geral_estoque VisaoGeralEstoque = new TELA_visao_geral_estoque();
            VisaoGeralEstoque.setVisible(true);
        } else if ("Entrada EPI Estoque".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_entrada_epi_estoque EntradaEpiEstoque = new TELA_entrada_epi_estoque();
            EntradaEpiEstoque.setVisible(true);
        } else if ("Saida para funcionarios".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_saida_epi_para_funcionarios SaidaParaFuncionarios = new TELA_saida_epi_para_funcionarios();
            SaidaParaFuncionarios.setVisible(true);
}       
    }//GEN-LAST:event_CB_estoqueActionPerformed

    private void cb_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_relatoriosActionPerformed
 String selectedOption = (String)  cb_relatorios.getSelectedItem();
 if ("Relatorio Entrega Funcionarios".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_relatorio_entrega_funcionarios entregaEstoque = new TELA_relatorio_entrega_funcionarios();
            entregaEstoque.setVisible(true);
        } else if ("Relatorio De Estoque".equals(selectedOption)) {
            TELA_menu.this.dispose();
           TELA_relatorio_estoque relatorioEstoque = new TELA_relatorio_estoque();
            relatorioEstoque.setVisible(true);
        }
    }//GEN-LAST:event_cb_relatoriosActionPerformed

    private void CB_listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_listasActionPerformed
        // TODO add your handling code here:
        if ("Visao Geral do Estoque".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_visao_geral_estoque VisaoGeralEstoque = new TELA_visao_geral_estoque();
            VisaoGeralEstoque.setVisible(true);
        } else if ("Entrada EPI Estoque".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_entrada_epi_estoque EntradaEpiEstoque = new TELA_entrada_epi_estoque();
            EntradaEpiEstoque.setVisible(true);
        } else if ("Saida para funcionarios".equals(selectedOption)) {
            TELA_menu.this.dispose();
            TELA_saida_epi_para_funcionarios SaidaParaFuncionarios = new TELA_saida_epi_para_funcionarios();
            SaidaParaFuncionarios.setVisible(true);
    }//GEN-LAST:event_CB_listasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_estoque;
    private javax.swing.JComboBox<String> CB_listas;
    private javax.swing.JButton btn_MN_cadastro_F;
    private javax.swing.JButton btn_MN_epi_entregue;
    private javax.swing.JComboBox<String> cb_relatorios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
