/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.telas.epi_gestor.telas;

/**
 *
 * @author Gabriel Resende
 */
public class tela_menu extends javax.swing.JFrame {

    /**
     * Creates new form tela_menu
     */
    public tela_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBTcadastrofuncionario = new javax.swing.JButton();
        JBTcadastroepi = new javax.swing.JButton();
        JBTrelatorioepimenu = new javax.swing.JButton();
        JBTepisentregue = new javax.swing.JButton();
        JBTrelatorioepiestoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBTcadastrofuncionario.setContentAreaFilled(false);
        JBTcadastrofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastrofuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(JBTcadastrofuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 90));

        JBTcadastroepi.setContentAreaFilled(false);
        JBTcadastroepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTcadastroepiActionPerformed(evt);
            }
        });
        jPanel1.add(JBTcadastroepi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 100));

        JBTrelatorioepimenu.setContentAreaFilled(false);
        JBTrelatorioepimenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTrelatorioepimenuActionPerformed(evt);
            }
        });
        jPanel1.add(JBTrelatorioepimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 120, 140));

        JBTepisentregue.setContentAreaFilled(false);
        JBTepisentregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTepisentregueActionPerformed(evt);
            }
        });
        jPanel1.add(JBTepisentregue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 110, 120));

        JBTrelatorioepiestoque.setContentAreaFilled(false);
        JBTrelatorioepiestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTrelatorioepiestoqueActionPerformed(evt);
            }
        });
        jPanel1.add(JBTrelatorioepiestoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel Resende\\Desktop\\tech tech\\EPI_Gestor\\EPI_Gestor\\src\\main\\java\\com\\telas\\sistema\\tela_menu.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTrelatorioepiestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTrelatorioepiestoqueActionPerformed
        // TODO add your handling code here:
        tela_menu.this.dispose();
        estoque_ JBTrelatorioepiestoque = new estoque_();
        JBTrelatorioepiestoque.setVisible(true);
    }//GEN-LAST:event_JBTrelatorioepiestoqueActionPerformed

    private void JBTcadastrofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastrofuncionarioActionPerformed
        // TODO add your handling code here:
        tela_menu.this.dispose();
        tela_cad_funcionarios JBTcadastrofuncionario = new tela_cad_funcionarios();
        JBTcadastrofuncionario.setVisible(true);
    }//GEN-LAST:event_JBTcadastrofuncionarioActionPerformed

    private void JBTcadastroepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTcadastroepiActionPerformed
        // TODO add your handling code here:
        tela_menu.this.dispose();
        tela_cad_epi JBTcadastroepi = new tela_cad_epi();
        JBTcadastroepi.setVisible(true);
    }//GEN-LAST:event_JBTcadastroepiActionPerformed

    private void JBTepisentregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTepisentregueActionPerformed
        // TODO add your handling code here:
        tela_menu.this.dispose();
        epi_em_estoque JBTepisentregue = new epi_em_estoque();
        JBTepisentregue.setVisible(true);
    }//GEN-LAST:event_JBTepisentregueActionPerformed

    private void JBTrelatorioepimenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTrelatorioepimenuActionPerformed
        // TODO add your handling code here:
        tela_menu.this.dispose();
        entrada_de_estoque JBTrelatorioepimenu = new entrada_de_estoque();
        JBTrelatorioepimenu.setVisible(true);
    }//GEN-LAST:event_JBTrelatorioepimenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTcadastroepi;
    private javax.swing.JButton JBTcadastrofuncionario;
    private javax.swing.JButton JBTepisentregue;
    private javax.swing.JButton JBTrelatorioepiestoque;
    private javax.swing.JButton JBTrelatorioepimenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
